version: '1.0'
services:
  solid:
    image: georgepacheco/solid7:1.0
    platform: linux/amd64
    container_name: 'solid'
    volumes:
      - .:/fot-solid
    expose:
      - "3000"
    ports:
      - '3000:3000'      
      - '3333:3333'
    entrypoint: sh -c "npm start -- -c config/file.json -f .data & sleep 20 && node ../fot-solid/dist/index.js"
    