version: '1.0'
services:
  solid_cloud:
    image: georgepacheco/solid-server:1.3.2
    env_file:
      .env
    platform: linux/amd64
    container_name: 'solid_cloud'
    volumes:
      - .:/solid
    expose:
      - "3010"      
    ports:         
      - '3333:3333'     
    entrypoint: bash -c "npm start -- -c config/file.json -f .data --seedConfig ../solid/seed.json & sleep 20 && node ../solid/dist/index.js"
    
    # entrypoint: bash -c "NODE_TLS_REJECT_UNAUTHORIZED=0 npm start -- -b https://192.168.0.111:3010 -c config/file-https.json -f .data --httpsKey config/certs/server.key --httpsCert config/certs/server.crt & sleep 20 & node ../solid/dist/index.js"        
    
    